export const PROMPTS_INT6066 = [
  "Has created a personal website or blog.",
  "Can name at least 3 different coding languages.",
  "Knows the meaning of design thinking.",
  "Loves bubble teas. What types?",
  "Has designed an app.",
  "Has more than 5 apps on their phone they've never used. What are they?",
  "Can explain what an API is.",
  "Has forgotten a password right after creating it.",
  "Has tried to zoom in on a paper photo with their fingers.",
  "Has accidentally \"liked\" something while stalking someone on social media.",
  "Has won a prize or award in a tech/design competition.",
  "Has multiple apps for the same purpose, just can't decide which to delete.",
  "Has used Inquiry-Based Learning in a classroom setting.",
  "Knows Universal Design for Learning (UDL).",
  "Can explain the difference between formative and summative assessments.",
  "Enjoys podcasts about technology.",
  "Subscribes to a technology or design magazine.",
  "Has a habit of jogging/swimming.",
  "Has created a meme.",
  "Has joined a fitness challenge app but only logged in once.",
  "Has kept too many browser tabs open \"just in case.\"",
  "Has made a typo in a password and then immediately questioned their entire memory.",
  "Has received a call and Googled the number instead of answering.",
  "Has changed a password, then immediately forgot the new one.",
  "Knows how to use a hashtag effectively.",
  "Has spent more time picking a movie than actually watching it.",
  "Has subscribed to a free trial and forgot to cancel it before being charged.",
  "Has used tech as an excuse (\"bad connection\") to leave an unwanted conversation.",
  "Has applied Bloom's Taxonomy in designing a curriculum.",
  "Has named AI assistant and refers to it like a member of the family. (e.g., will rename ChatGPT)",
  "Has tried to get existential answers from a chatbot, such as the meaning of life.",
  "Has been defeated by a captcha multiple times, leading to an identity crisis: \"Am I even human?\"",
  "Has spent more time trying to make an AI understand a command than it would have taken to do the task manually.",
  "Has participated in a virtual conference or webinar to present research / project findings.",
  "Knows what the Zone of Proximal Development (ZPD) is and how to use it.",
  "Has heard about Social Cognitive Theory."
];

export const PROMPTS_INT6136P = [
  "在工作中使用过 ChatGPT 或其他 AI 聊天机器人",
  "曾让 AI 帮忙起草过一封邮件",
  "能解释什么是「提示工程（Prompt Engineering）」",
  "认为在未来 5 年内，AI 会减少工作负担",
  "设计过一个应用程序（App）",
  "使用过 AI 生成图片或艺术作品",
  "能解释什么是 API",
  "刚创建密码就立刻忘记",
  "在家中使用过 Siri、Alexa 等语音助理",
  "在网上看过“深度伪造（Deepfake）”视频",
  "能用简单的话解释什么是“机器学习”",
  "同一用途装了多个 App，却一直纠结删哪一个",
  "给 AI 助手取过名字，并像家人一样称呼它（例如给 ChatGPT 改名）",
  "向 AI 工具咨询过职业发展建议",
  "认为 AI 被过度炒作了",
  "尝试过用 AI 生成旅行计划或行程安排",
  "订阅过科技类或设计类杂志",
  "有慢跑或游泳的习惯",
  "让 ChatGPT 写过一封情书 💌",
  "尝试过向 AI 要彩票号码 🎰",
  "让 AI 解释过一个笑话🤔",
  "向 AI 咨询过恋爱建议💘",
  "使用过 AI 决定晚餐吃什么🍲",
  "不小心把 AI 的错误直接复制进正式文件😅",
  "让 AI 生成了一个笑话，但自己没看懂😐",
  "问 AI 预测自己的未来🔮",
  "最近读过有关“AI 治理”或监管的内容",
  "在工作中参加过 AI 相关的培训或工作坊",
  "见过公司或机构开始采用 AI 工具",
  "关注或看过关于自动驾驶汽车或无人机的新闻",
  "尝试过用 AI 自动总结会议记录",
  "使用过 AI 分析就业市场趋势",
  "曾问过 AI：“你比我聪明吗？”🧠",
  "相信人类与 AI 协作能创造出比人类单独更好的成果",
  "知道什么是 RAG（检索增强生成，Retrieval-Augmented Generation）",
  "读过有关“智能体 AI（Agentic AI）”的内容"
];

export function getPrompts(roomCode) {
  const key = String(roomCode || "").toUpperCase().replace(/\s+/g, "");
  if (key.includes("6136")) return PROMPTS_INT6136P;
  return PROMPTS_INT6066;
}
