export const PROMPTS = [
  "Has created a personal website or blog.",
  "Can name at least 3 different coding languages.",
  "Knows the meaning of design thinking.",
  "Loves bubble teas. What types?",
  "Has designed an app.",
  "Has more than 5 apps on their phone they've never used. What are they?",
  "Can explain what an API is.",
  "Has forgotten a password right after creating it.",
  "Has tried to zoom in on a paper photo with their fingers.",
  "Has accidentally \"liked\" something while stalking someone on social media.",
  "Has won a prize or award in a tech/design competition.",
  "Has multiple apps for the same purpose, just can't decide which to delete.",
  "Has used Inquiry-Based Learning in a classroom setting.",
  "Knows Universal Design for Learning (UDL).",
  "Can explain the difference between formative and summative assessments.",
  "Enjoys podcasts about technology.",
  "Subscribes to a technology or design magazine.",
  "Has a habit of jogging/swimming.",
  "Has created a meme.",
  "Has joined a fitness challenge app but only logged in once.",
  "Has kept too many browser tabs open \"just in case.\"",
  "Has made a typo in a password and then immediately questioned their entire memory.",
  "Has received a call and Googled the number instead of answering.",
  "Has changed a password, then immediately forgot the new one.",
  "Knows how to use a hashtag effectively.",
  "Has spent more time picking a movie than actually watching it.",
  "Has subscribed to a free trial and forgot to cancel it before being charged.",
  "Has used tech as an excuse (\"bad connection\") to leave an unwanted conversation.",
  "Has applied Bloom's Taxonomy in designing a curriculum.",
  "Has named AI assistant and refers to it like a member of the family. (e.g., will rename ChatGPT)",
  "Has tried to get existential answers from a chatbot, such as the meaning of life.",
  "Has been defeated by a captcha multiple times, leading to an identity crisis: \"Am I even human?\"",
  "Has spent more time trying to make an AI understand a command than it would have taken to do the task manually.",
  "Has participated in a virtual conference or webinar to present research / project findings.",
  "Knows what the Zone of Proximal Development (ZPD) is and how to use it.",
  "Has heard about Social Cognitive Theory."
];
